version: '3'

services:
  web:
    build: .gitignore
    command: python src/genomic_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code

    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres



